version: "3.9"

services:

  db:
    image: postgres:17
    container_name: postgres-db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskdb

    ports:
      - "5432:5432"

    volumes:
      - task-data:/var/lib/postgresql/data

volumes:
  task-data: